version: '3.9'

services:

  redis:
    image: redis:latest
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    networks:
      - frontend
      - backend
      
      
  apache:
    image: httpd:latest
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
      
      
  postgres:
    image: postgres:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
      
networks:
  frontend:
  backend:
  
volumes:
  db_data:
